return PlaceObj('ModDef', {
    'title', "Mouse Cursor PS5 Xbox",
    'id', "MouseCursorPs5Xbox",
    'author', "fredware",
    'short_description', "TEST BUILD - NOT READY. Toggle a left-stick mouse cursor with R3; hold L3 / Xbox left-stick click for faster movement. PS5 and Xbox Series testing required.",
    'image', "Mod/MouseCursorPs5Xbox/Images/test-not-ready.png",
    'version', 14,
    'lua_revision', 350453,
    'saved_with_revision', 405907,
    'description', "Toggle a left-stick mouse cursor with R3 / right-stick click from the main menu (Tutorial, New Game, Load Game), setup screens, or gameplay. Mouse mode stays on between screens. Hold L3 / Xbox left-stick click for faster movement (default 2.5x). Configure speeds, size, response, smoothing and bindings in Options > Controls > Mouse Cursor PS5 Xbox. Cross / A: left click; Circle / B: right click; L1 / LB: wheel up; R1 / RB: wheel down; Options / Menu: Escape. R3 is reserved for the toggle while this mod is enabled. Uses a temporary PC interface and restores previous controls when switched off. PS5 and Xbox Series X|S runtime testing is still required; this release is not console-certified.",
    'last_changes', "Renamed the mod to Mouse Cursor PS5 Xbox with the MouseCursorPs5Xbox mod ID and mcpx code prefix. Cursor controls and behavior are unchanged; enable the new mod identity and configure its preferences after updating.",
    'default_options', {},
    'code', {
        "Code/mcpx_config.lua",
        "Code/mcpx_debug.lua",
        "Code/mcpx_settings.lua",
        "Code/mcpx_cursor.lua",
        "Code/mcpx_input.lua",
        "Code/mcpx_lifecycle.lua",
        "Code/mcpx_settings_ui.lua",
        "Code/MouseCursorPs5Xbox.lua",
    },
    'TagInterface', true,
})
